# Generated by Django 4.1.6 on 2023-03-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sit_ble_devices", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DistanceMeasureings",
            new_name="DistanceMeasurement",
        ),
    ]
