# Generated by Django 4.1.6 on 2023-03-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sit_ble_devices",
            "0002_rename_distancemeasureings_distancemeasurement",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="distancemeasurement",
            old_name="Simple Distance",
            new_name="distance",
        ),
    ]
