# Generated by Django 4.1.7 on 2023-03-29 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0005_alter_measurementtest_test_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementtestsettings",
            name="test_distance",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="measurementtestsettings",
            name="test_unit",
            field=models.CharField(
                blank=True, default="m", max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="measurementtestsettings",
            name="test_max_measurements",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="measurementtestsettings",
            name="test_min_measurements",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
