# Generated by Django 4.1.7 on 2023-03-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0006_measurementtestsettings_test_distance_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="measurementtest",
            name="comments",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
