# Generated by Django 4.1.7 on 2023-03-31 18:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sit_ble_devices", "0007_measurementtest_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MeasurementTestSettings",
            new_name="DeviceTestGroups",
        ),
        migrations.RenameModel(
            old_name="MeasurementTest",
            new_name="DeviceTests",
        ),
    ]
