# Generated by Django 4.1.7 on 2023-03-31 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0009_rename_test_settings_devicetests_test_group",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetests",
            name="test_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sit_ble_devices.devicetestgroups",
            ),
        ),
    ]
