# Generated by Django 4.1.7 on 2023-04-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0010_alter_devicetests_test_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicetestgroups",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="devicetests",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="distancemeasurement",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="devicetestgroups",
            name="comments",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
