# Generated by Django 4.1.7 on 2023-04-01 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0011_alter_devicetestgroups_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicetestgroups",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="devicetests",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="distancemeasurement",
            options={"ordering": ["created"]},
        ),
    ]
