# Generated by Django 4.1.7 on 2023-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0012_alter_devicetestgroups_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetestgroups",
            name="test_description",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
