# Generated by Django 4.1.7 on 2023-04-04 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0013_devicetestgroups_test_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetests",
            name="real_test_distance",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
