# Generated by Django 4.2.1 on 2023-06-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0014_devicetests_real_test_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="distancemeasurement",
            name="RecivedSignalStrengthIndex",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="firstPathIndex",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="nlos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="distancemeasurement",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test",
                to="sit_ble_devices.devicetests",
            ),
        ),
    ]
