# Generated by Django 4.2.1 on 2023-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0015_distancemeasurement_recivedsignalstrengthindex_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="distancemeasurement",
            name="error_distance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
