# Generated by Django 4.2.1 on 2023-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0017_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="UwbDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("device_name", models.CharField(max_length=30)),
                ("device_id", models.CharField(max_length=15)),
                (
                    "comments",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.DeleteModel(
            name="Device",
        ),
    ]
