# Generated by Django 4.2.1 on 2023-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0018_uwbdevice_delete_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uwbdevice",
            name="device_id",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
