# Generated by Django 4.2.1 on 2023-07-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0022_uwbdevice_calibrated_uwbdevice_rx_ant_delay_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Calibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("default", models.BooleanField(default=True)),
                ("tx_ant_delay", models.IntegerField(default=16385)),
                ("rx_ant_delay", models.IntegerField(default=16385)),
                ("temperature", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="uwbdevice",
            name="calibrated",
        ),
        migrations.RemoveField(
            model_name="uwbdevice",
            name="rx_ant_delay",
        ),
        migrations.RemoveField(
            model_name="uwbdevice",
            name="tx_ant_delay",
        ),
        migrations.AddField(
            model_name="uwbdevice",
            name="ant_calibraition",
            field=models.ManyToManyField(
                blank=True, to="sit_ble_devices.calibration"
            ),
        ),
    ]
