# Generated by Django 4.2.4 on 2023-09-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0023_calibration_remove_uwbdevice_calibrated_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibration",
            name="default",
        ),
        migrations.RemoveField(
            model_name="calibration",
            name="rx_ant_delay",
        ),
        migrations.RemoveField(
            model_name="calibration",
            name="tx_ant_delay",
        ),
        migrations.RemoveField(
            model_name="uwbdevice",
            name="ant_calibraition",
        ),
        migrations.AddField(
            model_name="calibration",
            name="comments",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="calibration",
            name="type",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="calibration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calibration",
                to="sit_ble_devices.calibration",
            ),
        ),
        migrations.AlterField(
            model_name="calibration",
            name="temperature",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="distancemeasurement",
            name="sequence",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CalibrationsDistances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("distance", models.FloatField()),
                (
                    "calibration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sit_ble_devices.calibration",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="initiator",
                        to="sit_ble_devices.uwbdevice",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="responder",
                        to="sit_ble_devices.uwbdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AntDelay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                ("default", models.BooleanField(default=True)),
                ("tx_ant_delay", models.IntegerField(default=16385)),
                ("rx_ant_delay", models.IntegerField(default=16385)),
                (
                    "calibration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sit_ble_devices.calibration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="uwbdevice",
            name="ant_delay",
            field=models.ManyToManyField(
                blank=True, to="sit_ble_devices.antdelay"
            ),
        ),
    ]
