# Generated by Django 4.2.4 on 2023-09-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0024_remove_calibration_default_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distancemeasurement",
            name="measurement",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
