# Generated by Django 4.2.4 on 2023-09-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0025_distancemeasurement_measurement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uwbdevice",
            name="ant_delay",
        ),
        migrations.AddField(
            model_name="antdelay",
            name="device",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sit_ble_devices.uwbdevice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calibration",
            name="iterations",
            field=models.IntegerField(default=100),
        ),
    ]
