# Generated by Django 4.2.4 on 2023-10-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0026_remove_uwbdevice_ant_delay_antdelay_device_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="distancemeasurement",
            name="initiator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="initiator",
                to="sit_ble_devices.uwbdevice",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="repsonder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="responder",
                to="sit_ble_devices.uwbdevice",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calibrationsdistances",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cali_initiator_device",
                to="sit_ble_devices.uwbdevice",
            ),
        ),
        migrations.AlterField(
            model_name="calibrationsdistances",
            name="responder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cali_responder_device",
                to="sit_ble_devices.uwbdevice",
            ),
        ),
    ]
