# Generated by Django 4.2.4 on 2023-10-05 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0027_distancemeasurement_initiator_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calibration",
            options={"ordering": ["created"]},
        ),
    ]
