# Generated by Django 4.2.4 on 2023-10-13 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0028_alter_calibration_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="distancemeasurement",
            old_name="repsonder",
            new_name="responder",
        ),
    ]
