# Generated by Django 4.2.7 on 2023-11-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0029_rename_repsonder_distancemeasurement_responder",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibration",
            name="comments",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="calibration",
            name="temperature",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
