# Generated by Django 4.2.7 on 2023-11-16 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0030_alter_calibration_comments_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calibrationsdistances",
            old_name="calibration",
            new_name="calibration_mod",
        ),
    ]
