# Generated by Django 4.2.7 on 2023-11-16 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0031_rename_calibration_calibrationsdistances_calibration_mod",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="antdelay",
            old_name="calibration",
            new_name="calibration_mod",
        ),
    ]
