# Generated by Django 4.2.7 on 2023-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0032_rename_calibration_antdelay_calibration_mod",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calibration",
            name="devices",
            field=models.ManyToManyField(
                blank=True, null=True, to="sit_ble_devices.uwbdevice"
            ),
        ),
    ]
