# Generated by Django 5.0.1 on 2024-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0033_calibration_devices"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetestgroups",
            name="test_measurement_type",
            field=models.CharField(default="ss_twr", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="measurement_type",
            field=models.CharField(default="ss_twr", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="antdelay",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="antdelay",
            name="rx_ant_delay",
            field=models.FloatField(default=5.13e-14),
        ),
        migrations.AlterField(
            model_name="antdelay",
            name="tx_ant_delay",
            field=models.FloatField(default=5.13e-14),
        ),
    ]
