# Generated by Django 5.0.1 on 2024-02-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0034_devicetestgroups_test_measurement_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calibration",
            name="measurement_type",
            field=models.CharField(default="ss_twr", max_length=30),
            preserve_default=False,
        ),
    ]
