# Generated by Django 5.0.1 on 2024-02-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0035_calibration_measurement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibration",
            name="devices",
            field=models.ManyToManyField(
                blank=True, to="sit_ble_devices.uwbdevice"
            ),
        ),
    ]
