# Generated by Django 5.0.1 on 2024-02-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0036_alter_calibration_devices"),
    ]

    operations = [
        migrations.RenameField(
            model_name="distancemeasurement",
            old_name="RecivedSignalStrengthIndex",
            new_name="first_path_index_final",
        ),
        migrations.RenameField(
            model_name="distancemeasurement",
            old_name="firstPathIndex",
            new_name="recived_signal_strength_index_final",
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="time_reply_1",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="time_reply_2",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="time_round_1",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="time_round_2",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
