# Generated by Django 5.0.1 on 2024-04-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0037_rename_recivedsignalstrengthindex_distancemeasurement_first_path_index_final_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calibration",
            name="calibration_type",
            field=models.CharField(
                choices=[
                    (
                        "Antenna Calibration (ASP014)",
                        "Antenna Calibration (ASP014)",
                    ),
                    (
                        "Antenna Calibration (PSO) - EDM",
                        "Antenna Calibration (PSO) - EDM",
                    ),
                    (
                        "Antenna Calibration (PSO) - ADS",
                        "Antenna Calibration (PSO) - ADS",
                    ),
                    ("Gauss-Newton (ADS)", "Gauss-Newton (ADS)"),
                ],
                default="Antenna Calibration (ASP014)",
                max_length=40,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="distancemeasurement",
            name="calibration",
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="calibration",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="calibration",
                to="sit_ble_devices.calibration",
            ),
        ),
    ]
