# Generated by Django 5.0.1 on 2024-04-03 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0039_alter_distancemeasurement_calibration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibration",
            name="type",
        ),
    ]
