# Generated by Django 5.0.1 on 2024-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sit_ble_devices", "0040_remove_calibration_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distancemeasurement",
            name="calibration",
        ),
        migrations.AddField(
            model_name="distancemeasurement",
            name="calibrations",
            field=models.ManyToManyField(
                blank=True,
                related_name="calibrations",
                to="sit_ble_devices.calibration",
            ),
        ),
    ]
