# Generated by Django 5.0.1 on 2024-05-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0041_remove_distancemeasurement_calibration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibration",
            name="calibration_type",
            field=models.CharField(
                choices=[
                    (
                        "Antenna Calibration (ASP014)",
                        "Antenna Calibration (ASP014)",
                    ),
                    (
                        "Antenna Calibration (PSO) - EDM",
                        "Antenna Calibration (PSO) - EDM",
                    ),
                    (
                        "Antenna Calibration (PSO) - ADS",
                        "Antenna Calibration (PSO) - ADS",
                    ),
                    (
                        "Antenna Calibration (GNA) - ADS",
                        "Antenna Calibration (GNA) - ADS",
                    ),
                    (
                        "Antenna Calibration (Simple)",
                        "Antenna Calibration (Simple)",
                    ),
                    (
                        "Antenna Calibration (Extended)",
                        "Antenna Calibration (Extended)",
                    ),
                    (
                        "Antenna Calibration (Two Device)",
                        "Antenna Calibration (Two Device)",
                    ),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="CalibrationMeasurements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("time_m21", models.FloatField()),
                ("time_m31", models.FloatField()),
                ("time_a21", models.FloatField()),
                ("time_a31", models.FloatField()),
                ("time_b21", models.FloatField()),
                ("time_b31", models.FloatField()),
                ("time_b_i", models.FloatField()),
                ("time_b_ii", models.FloatField()),
                ("time_c_i", models.FloatField()),
                ("time_c_ii", models.FloatField()),
                (
                    "calibrations",
                    models.ManyToManyField(
                        related_name="calibration",
                        to="sit_ble_devices.calibration",
                    ),
                ),
                (
                    "device_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="device_a",
                        to="sit_ble_devices.uwbdevice",
                    ),
                ),
                (
                    "device_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="device_b",
                        to="sit_ble_devices.uwbdevice",
                    ),
                ),
                (
                    "device_c",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="device_c",
                        to="sit_ble_devices.uwbdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
