# Generated by Django 5.0.1 on 2024-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0042_alter_calibration_calibration_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationmeasurements",
            name="measurement",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calibrationmeasurements",
            name="sequence",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calibrationmeasurements",
            name="calibrations",
            field=models.ManyToManyField(
                blank=True,
                related_name="calibration",
                to="sit_ble_devices.calibration",
            ),
        ),
    ]
