# Generated by Django 5.0.1 on 2024-05-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0043_calibrationmeasurements_measurement_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetests",
            name="antenna_delay_initator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="antenna_delay_initator",
                to="sit_ble_devices.antdelay",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="devicetests",
            name="antenna_delay_responder",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="antenna_delay_responder",
                to="sit_ble_devices.antdelay",
            ),
            preserve_default=False,
        ),
    ]
