# Generated by Django 5.0.1 on 2024-05-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0044_devicetests_antenna_delay_initator_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationmeasurements",
            name="time_reply_1",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calibrationmeasurements",
            name="time_reply_2",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calibrationmeasurements",
            name="time_round_1",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="calibrationmeasurements",
            name="time_round_2",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
