# Generated by Django 5.0.1 on 2024-05-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0045_calibrationmeasurements_time_reply_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationmeasurements",
            name="time_reply_1",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="calibrationmeasurements",
            name="time_reply_2",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="calibrationmeasurements",
            name="time_round_1",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="calibrationmeasurements",
            name="time_round_2",
            field=models.FloatField(default=0.0),
        ),
    ]
