# Generated by Django 5.0.1 on 2024-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sit_ble_devices",
            "0046_alter_calibrationmeasurements_time_reply_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationmeasurements",
            name="distance",
            field=models.FloatField(default=0.0),
        ),
    ]
