[tool.black]
line-length=79

[tool.isort]
profile = "black"

#Pylint section
[tool.pylint]
[tool.pylint.master]
ignore='old_test/*.py'


[tool.pylint.'BASIC']
const-naming-style='UPPER_CASE'
module-naming-style='camelCase'
class-naming-style='PascalCase'

[tool.pylint.'MESSAGES CONTROL']
disable = ['I1101', 'C0114', 'C0115', 'C0116']
