# Generated by Django 4.0.6 on 2022-07-25 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UwbDeviceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('channel_num', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (7, 5)], default=5)),
                ('pulse_rep_freq', models.CharField(choices=[('DWT_PRF_16M', 'DWT_PRF_16M'), ('DWT_PRF_64M', 'DWT_PRF_64M')], default='DWT_PRF_64M', max_length=15)),
                ('premable_length_tx', models.CharField(choices=[('DWT_PLEN_4096', 'DWT_PLEN_4096'), ('DWT_PLEN_2048', 'DWT_PLEN_2048'), ('DWT_PLEN_1024', 'DWT_PLEN_1024'), ('DWT_PLEN_512', 'DWT_PLEN_512'), ('DWT_PLEN_256', 'DWT_PLEN_256'), ('DWT_PLEN_128', 'DWT_PLEN_128'), ('DWT_PLEN_64', 'DWT_PLEN_64')], default='DWT_PLEN_2048', max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
