# Generated by Django 4.1 on 2022-10-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sit_settings", "0003_uwbdevicesettings_pdoa_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uwbdevicesettings",
            name="channel_num",
            field=models.IntegerField(choices=[(5, 5), (9, 9)], default=5),
        ),
        migrations.AlterField(
            model_name="uwbdevicesettings",
            name="data_rate",
            field=models.CharField(
                choices=[
                    ("DWT_BR_850K", "DWT_BR_850K"),
                    ("DWT_BR_6M8", "DWT_BR_6M8"),
                    ("DWT_BR_NODATA", "DWT_BR_NODATA"),
                ],
                default="DWT_BR_6M8",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="uwbdevicesettings",
            name="pdoa_mode",
            field=models.CharField(
                choices=[
                    ("DWT_PDOA_M0", "DWT_PDOA_M0"),
                    ("DWT_PDOA_M1", "DWT_PDOA_M1"),
                    ("DWT_PDOA_M3", "DWT_PDOA_M3"),
                ],
                default="DWT_PDOA_M0",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="uwbdevicesettings",
            name="premable_length_tx",
            field=models.CharField(
                choices=[
                    ("DWT_PLEN_4096", "DWT_PLEN_4096"),
                    ("DWT_PLEN_2048", "DWT_PLEN_2048"),
                    ("DWT_PLEN_1536", "DWT_PLEN_1536"),
                    ("DWT_PLEN_1024", "DWT_PLEN_1024"),
                    ("DWT_PLEN_512", "DWT_PLEN_512"),
                    ("DWT_PLEN_256", "DWT_PLEN_256"),
                    ("DWT_PLEN_128", "DWT_PLEN_128"),
                    ("DWT_PLEN_64", "DWT_PLEN_64"),
                    ("DWT_PLEN_32", "DWT_PLEN_32"),
                    ("DWT_PLEN_72", "DWT_PLEN_72"),
                ],
                default="DWT_PLEN_2048",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="uwbdevicesettings",
            name="pulse_rep_freq",
            field=models.CharField(
                choices=[
                    ("DWT_PRF_16M", "DWT_PRF_16M"),
                    ("DWT_PRF_64M", "DWT_PRF_64M"),
                    ("DWT_PRF_SCP", "DWT_PRF_SCP"),
                ],
                default="DWT_PRF_64M",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="uwbdevicesettings",
            name="sfd_mode",
            field=models.IntegerField(
                choices=[
                    ("DWT_SFD_IEEE_4A", "DWT_SFD_IEEE_4A"),
                    ("DWT_SFD_DW_8", "DWT_SFD_DW_8"),
                    ("DWT_SFD_DW_16", "DWT_SFD_DW_16"),
                    ("DWT_SFD_IEEE_4Z", "DWT_SFD_IEEE_4Z"),
                    ("DWT_SFD_LEN8", "DWT_SFD_LEN8"),
                    ("DWT_SFD_LEN16", "DWT_SFD_LEN16"),
                ],
                default=0,
            ),
        ),
    ]
