# Generated by Django 4.1 on 2022-10-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sit_settings", "0004_alter_uwbdevicesettings_channel_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uwbdevicesettings",
            name="sfd_mode",
            field=models.CharField(
                choices=[
                    ("DWT_SFD_IEEE_4A", "DWT_SFD_IEEE_4A"),
                    ("DWT_SFD_DW_8", "DWT_SFD_DW_8"),
                    ("DWT_SFD_DW_16", "DWT_SFD_DW_16"),
                    ("DWT_SFD_IEEE_4Z", "DWT_SFD_IEEE_4Z"),
                    ("DWT_SFD_LEN8", "DWT_SFD_LEN8"),
                    ("DWT_SFD_LEN16", "DWT_SFD_LEN16"),
                ],
                default="DWT_SFD_DW_8",
                max_length=15,
            ),
        ),
    ]
