name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set virtual environment
      run: echo "VIRTUAL_ENV=${Python_ROOT_DIR}" >> $GITHUB_ENV
    - name: Install uv
      run: pip install uv
    - name: Install dependencies
      run: uv pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')




  black:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose --exclude migrations "
